### ISSUE TITLE
Enhancement: Improve SVG Sprite compile time

### ISSUE THREAD

**Issue by patrickxchong** [11ta/11ta-template#18]
Hi @shanerobinson, first off, thank you for creating this template! It's been very helpful to kickstart my Eleventy journey. Would like to make a performance improvement suggestion: 

The current `svgsprite` shortcode runs each time a page is rendered, which leads to slow rebuilds in development. I managed to come up with a solution that compiles the svgsprite in 11ty's beforeBuild hook and only recompiles when a file is added/changed to the svg directory. I encapsulated the solution into a plugin for easy setup (https://github.com/patrickxchong/eleventy-plugin-svg-sprite), and it pretty much works as a drop in replacement for what you have here since I referred a lot to what you did (credited this template in the README as well). 

Would you be open to the idea of incorporating this plugin into this template? I would be happy to make a PR for this.

**Comment by shanerobinson** [comment]
Hi @patrickxchong and Thank You! A PR would be great! 
As you can tell, I'm not currently actively keeping up with updates or working in any of my repos right now. Other life issues taking priority. 

Thanks again and I will be happy to merge your PR!

**Comment by patrickxchong** [comment]
Hi @shanerobinson, appreciate your response! Hope all is well on your end. I've created a PR with the plugin, you can view it here. https://github.com/11ta/11ta-template/pull/20

**Comment by shanerobinson** [comment]
Merged! Thanks so much @patrickxchong

**Comment by patrickxchong** [comment]
Great, thanks for merging this @shanerobinson!
