### ISSUE TITLE
Netlify Deploy failed

### ISSUE THREAD

**Issue by rmlumley** [11ta/11ta-template#25]
11:10:26 AM: Build ready to start
11:10:28 AM: build-image version: 081db65c3e4ce8423fedb40e7689a87de6f84667
11:10:28 AM: build-image tag: v4.3.1
11:10:28 AM: buildbot version: 1523fa12d6de79e532ed0aff71973c5fbb8e58aa
11:10:28 AM: Building without cache
11:10:28 AM: Starting to prepare the repo for build
11:10:28 AM: No cached dependencies found. Cloning fresh repo
11:10:28 AM: git clone https://github.com/11ta/11ta-template
11:10:31 AM: Preparing Git Reference refs/heads/main
11:10:31 AM: Parsing package.json dependencies
11:10:32 AM: Starting build script
11:10:32 AM: Installing dependencies
11:10:32 AM: Python version set to 2.7
11:10:33 AM: Downloading and installing node v16.10.0...
11:10:33 AM: Downloading https://nodejs.org/dist/v16.10.0/node-v16.10.0-linux-x64.tar.xz...
11:10:33 AM: Computing checksum with sha256sum
11:10:33 AM: Checksums matched!
11:10:36 AM: Now using node v16.10.0 (npm v7.24.0)
11:10:36 AM: Started restoring cached build plugins
11:10:36 AM: Finished restoring cached build plugins
11:10:36 AM: Attempting ruby version 2.7.2, read from environment
11:10:38 AM: Using ruby version 2.7.2
11:10:38 AM: Using PHP version 8.0
11:10:38 AM: Started restoring cached node modules
11:10:38 AM: Finished restoring cached node modules
11:10:38 AM: Installing NPM modules using NPM version 7.24.0
11:10:40 AM: npm WARN old lockfile
11:10:40 AM: npm WARN old lockfile The package-lock.json file was created with an old version of npm,
11:10:40 AM: npm WARN old lockfile so supplemental metadata must be fetched from the registry.
11:10:40 AM: npm WARN old lockfile
11:10:40 AM: npm WARN old lockfile This is a one-time fix-up, please be patient...
11:10:40 AM: npm WARN old lockfile
11:11:01 AM: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
11:11:02 AM: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
11:11:02 AM: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
11:11:03 AM: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
11:11:04 AM: npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
11:11:04 AM: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
11:11:05 AM: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
11:11:08 AM: npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
11:11:10 AM: npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
11:11:13 AM: npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
11:11:23 AM: added 1506 packages, and audited 1507 packages in 44s
11:11:23 AM: 69 packages are looking for funding
11:11:23 AM:   run `npm fund` for details
11:11:23 AM: 4 moderate severity vulnerabilities
11:11:23 AM: To address all issues (including breaking changes), run:
11:11:23 AM:   npm audit fix --force
11:11:23 AM: Run `npm audit` for details.
11:11:23 AM: NPM modules installed
11:11:24 AM: Started restoring cached go cache
11:11:24 AM: Finished restoring cached go cache
11:11:24 AM: go version go1.16.5 linux/amd64
11:11:24 AM: go version go1.16.5 linux/amd64
11:11:24 AM: Installing missing commands
11:11:24 AM: Verify run directory
11:11:25 AM: ​
11:11:25 AM: ────────────────────────────────────────────────────────────────
11:11:25 AM:   Netlify Build                                                 
11:11:25 AM: ────────────────────────────────────────────────────────────────
11:11:25 AM: ​
11:11:25 AM: ❯ Version
11:11:25 AM:   @netlify/build 18.13.6
11:11:25 AM: ​
11:11:25 AM: ❯ Flags
11:11:25 AM:   baseRelDir: true
11:11:25 AM:   buildId: 6155e172a8c35c32a3e7e953
11:11:25 AM:   deployId: 6155e172a8c35c32a3e7e955
11:11:25 AM: ​
11:11:25 AM: ❯ Current directory
11:11:25 AM:   /opt/build/repo
11:11:25 AM: ​
11:11:25 AM: ❯ Config file
11:11:25 AM:   /opt/build/repo/netlify.toml
11:11:25 AM: ​
11:11:25 AM: ❯ Context
11:11:25 AM:   production
11:11:25 AM: ​
11:11:25 AM: ────────────────────────────────────────────────────────────────
11:11:25 AM:   1. build.command from netlify.toml                            
11:11:25 AM: ────────────────────────────────────────────────────────────────
11:11:25 AM: ​
11:11:25 AM: $ npm run build
11:11:26 AM: > sr-11ty-tailwind-alpine-template@1.0.0 build
11:11:26 AM: > run-s clean build:* --print-label
11:11:26 AM: [clean         ]
11:11:26 AM: [clean         ] > sr-11ty-tailwind-alpine-template@1.0.0 clean
11:11:26 AM: [clean         ] > rimraf dist
11:11:26 AM: [clean         ]
11:11:27 AM: [build:webpack ]
11:11:27 AM: [build:webpack ] > sr-11ty-tailwind-alpine-template@1.0.0 build:webpack
11:11:27 AM: [build:webpack ] > webpack  --mode production
11:11:27 AM: [build:webpack ]
11:11:29 AM: [build:webpack ] Hash: 0669b74486a472b65755
11:11:29 AM: [build:webpack ] Version: webpack 4.46.0
11:11:29 AM: [build:webpack ] Time: 2067ms
11:11:29 AM: [build:webpack ] Built at: 09/30/2021 4:11:29 PM
11:11:29 AM: [build:webpack ]   Asset      Size  Chunks             Chunk Names
11:11:29 AM: [build:webpack ] main.js  26.9 KiB       0  [emitted]  main
11:11:29 AM: [build:webpack ] Entrypoint main = main.js
11:11:29 AM: [build:webpack ] [0] ./src/assets/scripts/main.js 18 bytes {0} [built]
11:11:29 AM: [build:webpack ]     + 1 hidden module
11:11:30 AM: [build:eleventy]
11:11:30 AM: [build:eleventy] > sr-11ty-tailwind-alpine-template@1.0.0 build:eleventy
11:11:30 AM: [build:eleventy] > ELEVENTY_ENV=production eleventy
11:11:30 AM: [build:eleventy]
11:11:31 AM: [build:eleventy] (node:1511) [DEP0128] DeprecationWarning: Invalid 'main' field in '/opt/build/repo/node_modules/emitter-mixin/package.json' of 'y'. Please either fix that or report it to the module author
11:11:31 AM: [build:eleventy] (Use `node --trace-deprecation ...` to show where the warning was created)
11:11:32 AM: [build:eleventy] Writing dist/feed.xml from ./src/feed.njk.
11:11:33 AM: [build:eleventy] Writing dist/about/index.html from ./src/about.md.
11:11:33 AM: [build:eleventy] Writing dist/blog/index.html from ./src/blog.njk.
11:11:33 AM: [build:eleventy] Writing dist/contact/index.html from ./src/contact.njk.
11:11:33 AM: [build:eleventy] Writing dist/thankyou/index.html from ./src/thankyou.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/03/wrap-and-columns-shortcodes/index.html from ./src/posts/2020-09-03-columns.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/02/managing-social-share-author-and-footer-icons/index.html from ./src/posts/2020-09-02-manage-social-and-footer-icons.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/05/blockquotes-shortcodes/index.html from ./src/posts/2020-09-05-blockquotes.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/09/svg-shortcode/index.html from ./src/posts/2020-09-09-svg-shortcode.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/01/color-settings/index.html from ./src/posts/2020-09-01-manage-color-settings.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/07/full-frontmatter-example/index.html from ./src/posts/2020-09-07-full-frontmatter-example.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/10/site-meta-og-and-twitter-cards/index.html from ./src/posts/2020-09-10-meta-og-twitter.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/04/description-list-shortcodes/index.html from ./src/posts/2020-09-04-description-lists.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/06/featured-post-images/index.html from ./src/posts/2020-09-06-featured-images.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/11/manage-hero-graphics-carousels-splits-and-video/index.html from ./src/posts/2020-09-11-manage-hero.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/12/configuring-tailwindcss/index.html from ./src/posts/2020-09-12-tailwind.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/08/youtube-video-embed/index.html from ./src/posts/2020-09-08-youtube-embed.md.
11:11:33 AM: [build:eleventy] Writing dist/2020/09/20/v110-brings-draft-posts/index.html from ./src/posts/2020-09-20-draft-posts.md.
11:11:33 AM: [build:eleventy] Writing dist/authors/shane-robinson/index.html from ./src/authors.njk.
11:11:33 AM: [build:eleventy] Writing dist/404.html from ./src/404.md.
11:11:33 AM: [build:eleventy] Writing dist/tags/index.html from ./src/tags-list.njk.
11:11:33 AM: [build:eleventy] Writing dist/index.html from ./src/index.md.
11:11:33 AM: [build:eleventy] Writing dist/tags/all/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/blog/1/index.html from ./src/blog.njk.
11:11:33 AM: [build:eleventy] Writing dist/authors/roxanne-darling/index.html from ./src/authors.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/shortcodes/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/wrap/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/columns/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/social/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/svg/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/structure/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/blockquote/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/emoji/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/markdown/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/colors/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/customization/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/tailwindcss/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/lighthouse/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/frontmatter/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/hero/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/featured-image/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/meta/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/open-graph/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/twitter/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/video/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/carousel/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/slider/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/youtube/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/embed/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Writing dist/tags/tagList/index.html from ./src/tags.njk.
11:11:33 AM: [build:eleventy] Copied 53 files / Wrote 50 files in 2.25 seconds (45.0ms each, v0.11.1)
11:11:34 AM: [build:postcss ]
11:11:34 AM: [build:postcss ] > sr-11ty-tailwind-alpine-template@1.0.0 build:postcss
11:11:34 AM: [build:postcss ] > NODE_ENV=production postcss src/assets/css/tailwind.css -o dist/assets/tailwind.css
11:11:34 AM: [build:postcss ]
11:11:34 AM: [build:postcss ] postcss-import: postcss.plugin was deprecated. Migration guide:
11:11:34 AM: [build:postcss ] https://evilmartians.com/chronicles/postcss-8-plugin-migration
11:11:34 AM: [build:postcss ] postcss-functions: postcss.plugin was deprecated. Migration guide:
11:11:34 AM: [build:postcss ] https://evilmartians.com/chronicles/postcss-8-plugin-migration
11:11:34 AM: [build:postcss ] postcss-plugin-purgecss: postcss.plugin was deprecated. Migration guide:
11:11:34 AM: [build:postcss ] https://evilmartians.com/chronicles/postcss-8-plugin-migration
11:11:34 AM: [build:postcss ] postcss-nested: postcss.plugin was deprecated. Migration guide:
11:11:34 AM: [build:postcss ] https://evilmartians.com/chronicles/postcss-8-plugin-migration
11:11:34 AM: [build:postcss ] autoprefixer: postcss.plugin was deprecated. Migration guide:
11:11:34 AM: [build:postcss ] https://evilmartians.com/chronicles/postcss-8-plugin-migration
11:11:35 AM: [build:postcss ] cssnano: postcss.plugin was deprecated. Migration guide:
11:11:35 AM: [build:postcss ] https://evilmartians.com/chronicles/postcss-8-plugin-migration
11:11:35 AM: [build:postcss ]
11:11:35 AM: [build:postcss ] warn - You have enabled experimental features: applyComplexClasses
11:11:35 AM: [build:postcss ] warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.
11:11:36 AM: [build:postcss ]
11:11:36 AM: [build:postcss ] warn - The `conservative` purge mode will be removed in Tailwind 2.0.
11:11:36 AM: [build:postcss ] warn - Please switch to the new `layers` mode instead.
11:11:37 AM: [build:postcss ] TypeError: Cannot read properties of undefined (reading 'unprefixed')
11:11:37 AM: [build:postcss ]     at /opt/build/repo/src/assets/css/tailwind.css:1:1
11:11:37 AM: [build:postcss ]     at Prefixes.unprefixed (/opt/build/repo/node_modules/autoprefixer/lib/prefixes.js:372:39)
11:11:37 AM: [build:postcss ]     at /opt/build/repo/node_modules/autoprefixer/lib/processor.js:400:40
11:11:37 AM: [build:postcss ]     at /opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:72:18
11:11:37 AM: [build:postcss ]     at /opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:55:18
11:11:37 AM: [build:postcss ]     at Rule.each (/opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:41:16)
11:11:37 AM: [build:postcss ]     at Rule.walk (/opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:52:17)
11:11:37 AM: [build:postcss ]     at /opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:60:24
11:11:37 AM: [build:postcss ]     at Root.each (/opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:41:16)
11:11:37 AM: [build:postcss ]     at Root.walk (/opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:52:17)
11:11:37 AM: [build:postcss ]     at Root.walkDecls (/opt/build/repo/node_modules/postcss-cli/node_modules/postcss/lib/container.js:70:19) {
11:11:37 AM: [build:postcss ]   postcssNode: Declaration {
11:11:37 AM: [build:postcss ]     raws: { before: '\n  ', between: ': ', after: '\n  ' },
11:11:37 AM: [build:postcss ]     type: 'decl',
11:11:37 AM: [build:postcss ]     parent: Rule {
11:11:37 AM: [build:postcss ]       raws: [Object],
11:11:37 AM: [build:postcss ]       type: 'rule',
11:11:37 AM: [build:postcss ]       nodes: [Array],
11:11:37 AM: [build:postcss ]       source: [Object],
11:11:37 AM: [build:postcss ]       selector: 'html',
11:11:37 AM: [build:postcss ]       parent: [Root],
11:11:37 AM: [build:postcss ]       lastEach: 34,
11:11:37 AM: [build:postcss ]       indexes: [Object],
11:11:37 AM: [build:postcss ]       _autoprefixerDisabled: false,
11:11:37 AM: [build:postcss ]       [Symbol(my)]: true
11:11:37 AM: [build:postcss ]     },
11:11:37 AM: [build:postcss ]     source: { start: [Object], input: [Input], end: [Object] },
11:11:37 AM: [build:postcss ]     prop: 'line-height',
11:11:37 AM: [build:postcss ]     value: '1.15',
11:11:37 AM: [build:postcss ]     _autoprefixerDisabled: false,
11:11:37 AM: [build:postcss ]     [Symbol(my)]: true
11:11:37 AM: [build:postcss ]   }
11:11:37 AM: [build:postcss ] }
11:11:37 AM: ERROR: "build:postcss" exited with 1.
11:11:37 AM: ​
11:11:37 AM: ────────────────────────────────────────────────────────────────
11:11:37 AM:   "build.command" failed                                        
11:11:37 AM: ────────────────────────────────────────────────────────────────
11:11:37 AM: ​
11:11:37 AM:   Error message
11:11:37 AM:   Command failed with exit code 1: npm run build
11:11:37 AM: ​
11:11:37 AM:   Error location
11:11:37 AM:   In build.command from netlify.toml:
11:11:37 AM:   npm run build
11:11:37 AM: ​
11:11:37 AM:   Resolved config
11:11:37 AM:   build:
11:11:37 AM:     command: npm run build
11:11:37 AM:     commandOrigin: config
11:11:37 AM:     publish: /opt/build/repo/dist
11:11:37 AM:     publishOrigin: config
11:11:38 AM: Caching artifacts
11:11:38 AM: Started saving node modules
11:11:38 AM: Finished saving node modules
11:11:38 AM: Started saving build plugins
11:11:38 AM: Finished saving build plugins
11:11:38 AM: Started saving pip cache
11:11:38 AM: Finished saving pip cache
11:11:38 AM: Started saving emacs cask dependencies
11:11:38 AM: Finished saving emacs cask dependencies
11:11:38 AM: Started saving maven dependencies
11:11:38 AM: Finished saving maven dependencies
11:11:38 AM: Started saving boot dependencies
11:11:38 AM: Finished saving boot dependencies
11:11:38 AM: Started saving rust rustup cache
11:11:38 AM: Finished saving rust rustup cache
11:11:38 AM: Started saving go dependencies
11:11:38 AM: Finished saving go dependencies
11:11:40 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:11:40 AM: Creating deploy upload records
11:11:40 AM: Failing build: Failed to build site
11:11:40 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
11:11:40 AM: Finished processing build request in 1m12.242344826s

**Comment by tattooseoul** [comment]
Same issue here

**Comment by shanerobinson** [comment]
Hi. Sorry about this... Thanks for letting me know!
You can see I haven't paid any attention to this repo in over a year. 😕
A quick scan shows a problem in the "build:postcss" script. There's been a LOT of updates to PostCSS in the past year. 
I'll add it to my task list and hopefully get to it this week.

**Comment by niktayv** [comment]
This happens locally as well. I just generated a new project with "Use this template" button and followed the instructions in the Readme. Running `npm run dev` failed with the same error:
```
[build:postcss ] TypeError: Cannot read properties of undefined (reading 'unprefixed')
```
Googling this, I came across [this issue](https://github.com/postcss/autoprefixer/issues/1359), where they finally mention a Stackoverflow [question](https://stackoverflow.com/q/64057023/1008341) .

I tried various options from the answers to this question, but apparently only downgrading Autoprefixer as suggested in the [accepted answer](https://stackoverflow.com/a/64075012/1008341) worked for me:
```
"autoprefixer": "^9.0.0"
```
Now I can run `npm run dev` without errors.

**Comment by shanerobinson** [comment]
Sorry for taking so long to deal with this. 
I've refactored and simplified, removed babel, webpack, postcss, autoprefixer, etc. Everything works both locally and it deploys correctly. 

There remains an issue with 'nth-check' but from all my searching it seems this is a problem with 'audit' and not really a security risk at this point.

**Comment by shanerobinson** [comment]
PS: This should work perfectly if you either pull the latest updates or clone it again
