### ISSUE TITLE
colors.js data does not affect site

### ISSUE THREAD

**Issue by beh333** [11ta/11ta-template#28]
Thanks for a great Eleventy site-starter.
It seems that many things (most things?) from colors.js have no effect. For example, according to colors.js, the text in the nav menu should be teal-500, but on both my instance and the published demo site, the nav menu text is grey.
I am new to Eleventy, so I am not sure how all the pieces fit together, but I think the problems with colors.js may reflect a systemic issue with integrating javascript data into the templates?

**Comment by shanerobinson** [comment]
Now that I've refactored and simplified this repo and everything is updated and working, I'll take a look at this and try to provide better instructions. 

To be continued...

**Comment by shanerobinson** [comment]
So the instructions are already there in the `colors.js` file. 

If you read that again you'll see there are 2 sets of colors for each of the elements: **xxxDefault** and **xxxCustom***

If **xxxCustom** exists it overwrites **xxxDefault**.

The reason I set it up this way is so you can always keep the default settings right there in case you want to revert back to them. 

I've included a screen shot with a box around the instruction details, and how **navDefault** is overwritten by **navCustom**. 

If you change the colors in **navCustom** you'll see they update the Nav colors. 

![Cursor_and_colors_js_—_11ta-template](https://user-images.githubusercontent.com/93786/196546288-00aa36e3-03a1-4636-95b9-896df72d5463.jpg)
