### ISSUE TITLE
Enhancement/Feature Request-Algolia Netlify plugin

### ISSUE THREAD

**Issue by theapplegates** [11ta/11ta-template#3]
Would this work for searching? 
https://github.com/algolia/algoliasearch-netlify#readme

I use Algolia on a few sites, but it was always built in. All I did was supply the API keys. I don't know how to make the search field/box own each page. I'm not a developer.

It seems to be Netlify only, but a lot of users use that site.

Thanks
Paul

**Comment by shanerobinson** [comment]
@theapplegates I'm definitely planning to integrate the Algolia search plugin! 😃

**Comment by shanerobinson** [comment]
I've decided NOT to implement Algolia at this time. Others are invited to implement that if they feel search is important to their implementations.
