### ISSUE TITLE
Navigation Menu Problem on Firefox 83.0 Ubuntu

### ISSUE THREAD

**Issue by treb0r** [11ta/11ta-template#4]
Came across this issue on Firefox 83.0.

Works fine in Chrome on Ubuntu.
![11TA-screenshot-firefox-linux](https://user-images.githubusercontent.com/610729/101330610-b63be700-386a-11eb-8105-50995b935c84.jpg)

**Comment by shanerobinson** [comment]
Oh wow... Can confirm in my FF 83.0 on MacOS Big Sur. 
Thanks for pointing this out! Something wonky with my TailwindCSS breakpoints.

**Comment by shanerobinson** [comment]
Fixed in https://github.com/11ta/11ta-template/commit/c0e19f1c92a7136e50d95ebfb4a9551dd201a085
