### ISSUE TITLE
main.js 404 breaks alpine

### ISSUE THREAD

**Issue by MMcKinney** [11ta/11ta-template#47]
src/assets/scripts/main.js isn't making it to dist/assets

replicated here: https://11ta.netlify.app/
the hamburger menu doesn't work

I fixed my build by adding a passthrough copy of cdn.min.js and using that instead of main.js for now

eleventyConfig.addPassthroughCopy({
    './node_modules/alpinejs/dist/cdn.min.js': 'assets/alpine.js',
})
![Capture](https://user-images.githubusercontent.com/1205971/230019647-dfa3d24b-18cf-40cd-9ad3-3843108cdbcf.PNG)

**Comment by shanerobinson** [comment]
Thanks for pointing this out. I just removed main.js and pointed to the CDN. I just don't have the time to deal with it any other way. 😀
